### PR TITLE
add a Dockerfile to do the conversion

### PR DESCRIPTION
**Pull request by SvenDowideit**

### CODE REVIEW

**Comment by tianon** [comment]
This needs a DCO, @SvenDowideit

**Comment by tianon** [comment]
And, these man pages are already part of hack/make/ubuntu, so we need to do more than just add a Dockerfile

**Comment by tianon** [comment]
@ipbabble once you've rebased your branch, I can make a new PR off it to fix hack/make/ubuntu :)

**Comment by ipbabble** [comment]
Ack. I'll be back online, fully, in a short while. I'll ping you on #docker-dev if I have trouble.

**Comment by tianon** [comment]
Sounds good :)

**Comment by SvenDowideit** [comment]
@ipbabble I assume you'll close this PR as you've subsumed its intent?

(can you please specify a tag for the `FROM fedora` so we know what its based on?)

also - the docker project itself is using (or moving to use) debian based containers - so when its migrated into the main build, its likely to go there too :)

**Comment by ipbabble** [comment]
I hope to finish it up today. Had some issues with my commit last night and I have some cleaning up to do.

**Pull request closed without merging**
